# Generated by Django 5.1.6 on 2025-03-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triloka', '0001_initial'),
    ]

    operations = [
    ]
