# Generated by Django 5.1.6 on 2025-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triloka', '0002_auto_20250325_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='willing_to_donate_blood',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
