# Generated by Django 5.1.6 on 2025-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triloka', '0003_userprofile_willing_to_donate_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
