# Generated by Django 5.1.6 on 2025-03-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triloka', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(),
        ),
    ]
