# Generated by Django 5.1.6 on 2025-03-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triloka', '0004_alter_userpoint_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['date']},
        ),
    ]
