# Generated by Django 5.1.6 on 2025-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triloka', '0005_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
