# Generated by Django 5.1.6 on 2025-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triloka', '0006_gallery_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='category',
            field=models.CharField(choices=[('Participation', 'Participation'), ('Electivemember', 'Electivemember'), ('Joining', 'Joining'), ('Willingtodonateblood', 'Willingtodonateblood'), ('Fees', 'Fees'), ('Achievement', 'Achievement'), ('Leadership', 'Leadership'), ('DonateParticipation', 'DonateParticipation')], max_length=50),
        ),
    ]
