# Generated by Django 5.1.6 on 2025-09-24 13:30
from django.utils import timezone
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('triloka', '0007_alter_userpoint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
  
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),

            preserve_default=False,
        ),
      
    migrations.CreateModel(
        name='WeeklyTask',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('month', models.CharField(max_length=20)),
            ('week', models.CharField(max_length=20)),
            ('total', models.IntegerField(default=0)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triloka.userprofile')),
        ],
    ),


    ]
